Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,9 @@
-#!/bin/bash -x
+#!/bin/bash
 # bin/compile <build-dir> <cache-dir>
+
+set -e            # fail fast
+set -o pipefail   # do not ignore exit codes when piping output
+set -x          # enable debugging
 
 BUILD_DIR=$1
 CACHE_DIR=$2
